spring:
  profiles: 
    active:
      - dev

---

server:
  port: 9031
spring:
  profiles: dev
  application: 
    name: microservicescloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka
 
---

server:
  port: 9032
spring:
  profiles: test
  application: 
    name: microservicescloud-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka
 
