server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.lx.macroServices.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///microServices0?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200