server:
  port: 9021

spring:
  application:
    name: microservicescloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xiaoxin-99/MicroServicesCloud.git
#          force-pull: true
          private-key: id_rsa
          search-paths: common/config
      label: master




